#!/bin/sh -e

ZWACONF=./.zwaconf

TARGET=

set -e

if [ -f $ZWACONF ]; then
  . $ZWACONF
fi

if [ -z "$TARGET" ]; then
  TARGET=$PWD/out
fi

cmd=$1

CONFIGURATION=
if [ `echo "$TGZ_BUILD_OPTS" | grep -ow debug` == "debug" ]; then
  CONFIGURATION="Debug"
  echo " === Debug build with configuration: '$CONFIGURATION' === "
else
  CONFIGURATION="Release"
  echo " === Release build with configuration: '$CONFIGURATION' === "
fi

shift
case "$cmd" in
  get-version)
    get_version
    ;;
  prepare-dist)
    VERSION=`get_version`
    ;;
  dist-exclude-list|build-exclude-list)
    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ;;
  bootstrap)
    ;;
  configure)
    ;;
  make)
    if [ -z "$1" ]; then
      cmd.exe /c msbuild winbuild\\win32\\vs10\\libzorpll.vcxproj /p:Configuration="$CONFIGURATION"

    else
      case $1 in
        clean)
          ;;
        distclean)
          ;;
        install)
          cmd.exe /c msbuild winbuild\\win32\\vs10\\libzorpll.vcxproj /t:ZbsInstall /p:Configuration="$CONFIGURATION"

          ;;
      esac
    fi
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
